### ISSUE TITLE
2020-10-06:Reviewer for Afrikaans submission

### ISSUE THREAD

**Issue by jsteyn** [carpentries/glosario#105]
I noticed that you don't have any reviewers for Afrikaans. I would like to volunteer. How do I go about that?

**Comment by fmichonneau** [comment]
that would be great! Thank you.
I'm going to add you to the pull request template.

**Comment by jsteyn** [comment]
Hiya! That is great. Thank you very much. 
Just one question. Who reviews my pull requests?

**Comment by fmichonneau** [comment]
Currently, you are the only one who has contributed entries in Afrikaans so you'll be able to review your own pull requests in Afrikaans. For the other languages, the listed editors will review your pull requests.

**Comment by fmichonneau** [comment]
@jsteyn I invited you to a GitHub team that will provide you with write and review access to this repository.

**Comment by elletjies** [comment]
@all-contributors please add @jsteyn question
