### ISSUE TITLE
2020-10-07: add glosario definition in Afrikaans

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/glosario#108]
@jsteyn could you please add a description of glosario in Afrikaans? 

this file needs to be edited: https://github.com/carpentries/glosario/blob/master/af.md 
using content from here https://github.com/carpentries/glosario/blob/master/en.md

**Comment by jsteyn** [comment]
All done #113.

**Comment by fmichonneau** [comment]
thank you!
