### ISSUE TITLE
7-10-2020: Adding a definition in Arabic to the existing terms

### ISSUE THREAD

**Issue by BatoolMM** [carpentries/glosario#115]
It would be amazing if Arabic is also included in `glosario`. However, Arabic uses unique characters, might not be supported in `glosario`. If it's alright with you, I am happy to add a definition in Arabic (`ar`) to the existing terms in the `yml` file?

**Comment by zkamvar** [comment]
I believe Arabic should be supported as it can be represented in a UTF-8 character set, so if you have some translations, we would be more than happy to receive them!

**Comment by elletjies** [comment]
@all-contributors please add @BatoolMM question
