### ISSUE TITLE
`glosario.html` is not in the repo

### ISSUE THREAD

**Issue by ian-flores** [carpentries/glosario#16]
`index.md` renders `glosario.html` but it's not part of the repo. @gvwilson do we need to write `glosario.html` or is there a copy on a local computer?

**Comment by gvwilson** [comment]
`index.md` includes `glossary.html`, which is in `_includes/glossary.html`. When I run `bundle exec jekyll serve` and go to http://localhost:4000 to preview, I see the glossary. Should I change the name of the included file to be `glosario.html` ?
