### ISSUE TITLE
2020-11-02: add links by letter

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/glosario#196]
Create a way to jump directly to a letter in the glossary?
What does it look like for non-Latin alphabets?

**Comment by baileythegreen** [comment]
@fmichonneau I like it (and, as I'm off work this week, am playing around with ideas for implementation, but here are some thoughts:

- It also needs to handle entries that start with a number or punctuation; currently the glossary contains `+1` and `68_95_997_rule`.
- Unicode has encodings for some non-Latin languages (I didn't find any for Japanese/Chinese dialects, but they have [Arabic](https://en.wikipedia.org/wiki/Arabic_script_in_Unicode) and things like German, which is non-Latin, are possible if you use the Latin-supplement or one of the Extended encodings.
- There should be a set of links for jumping around (obviously), but these either need to be 'fixed' somewhere (so if I jump to `J`, I can then still easily jump to `C`, or we need to have links back to the top (where the links presumably reside) throughout the document (more annoying, I think). This could be accomplished using the `fixed` or `sticky` options for the [CSS `position` property](https://www.w3schools.com/css/css_positioning.asp), depending on what seems better.

**Comment by baileythegreen** [comment]
@fmichonneau I've implemented a version of this [here](https://baileythegreen.github.io/glosario). I had to modify layout and CSS files as well as some HTML content files, but it's dynamic, it works in all of the languages, and I even fixed some other problems with the HTML, like the text overflowing the page.

**Comment by fmichonneau** [comment]
that looks good! Could you please open a pull request so we can review the changes that would require?

**Comment by baileythegreen** [comment]
@fmichonneau I may have kept going and also made it mobile-device-friendly. Currently the button at the top references my fork's URL (a workaround to prevent an error when I tested it locally), but I'll fix it so that's not the case later.

**Comment by fmichonneau** [comment]
closed by #207
