### ISSUE TITLE
26-11-20: Arabic terms for merged PR #218 and PR #223 aren't rendered in the website.

### ISSUE THREAD

**Issue by BatoolMM** [carpentries/glosario#225]
This is to report a bug in the `glosario` repo.

It seems that recently merged PRs (PR #218 and PR #223) for Arabic translation aren't rendered on the website. In order to examine the issue, I tried to build the website locally but it's complaining. 
```
GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  Liquid Exception: "<USERNAME>/<PROJECT>" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys. in /_layouts/page.html
jekyll 3.9.0 | Error:  "<USERNAME>/<PROJECT>" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys.
```
This may have to be related to the changes introduced in PR #207 for `letter links`.  I also can't see the `letter links` in my Chrome browser.  

My apologies if no enough details are given in this report.

**Comment by baileythegreen** [comment]
@Batool, the repository identifier may need to be modified in your local clone to get it to render locally. I keep having to change it to baileythegreen/glosario to get it to render.

Not seeing the links in your browser is odd. I can see them in mine right now.
<img width="891" alt="Screen Shot 2020-11-26 at 12 21 08" src="https://user-images.githubusercontent.com/12277715/100350504-e4efcd00-2fe1-11eb-87ba-96b180873996.png">

**Comment by baileythegreen** [comment]
@BatoolMM Can you attach a screenshot of what you see in the browser?

**Comment by BatoolMM** [comment]
@baileythegreen, this is strange!

<img width="1280" alt="Screenshot 2020-11-26 at 15 27 15" src="https://user-images.githubusercontent.com/53487593/100351053-df9f7c00-2ffb-11eb-9d0f-e3b13651a910.png">

**Comment by baileythegreen** [comment]
@BatoolMM The strangest part for me is the url I see in your picture. Try this link:

https://carpentries.github.io/glosario/ar/

**Comment by baileythegreen** [comment]
Update: I tried your url, and it looks like what the site looked like before I did things to it. I think that is just the html file, without any of the CSS styling (and therefore no letter links). No idea why that doesn't include all of the new terms.

**Comment by baileythegreen** [comment]
For future reference, the correct form for the website url is:

https://carpentries.github.io/glosario

**Comment by BatoolMM** [comment]
It makes sense now but my `url` is the one displayed on the main page `about` of the repo (top right).

<img width="1280" alt="Screenshot 2020-11-26 at 15 41 25" src="https://user-images.githubusercontent.com/53487593/100352516-27bf9e00-2ffe-11eb-9832-e940de85ae6d.png">

**Comment by baileythegreen** [comment]
@BatoolMM The url you see on that page is set by a user in one of the 'About' fields, and so it is possible for it to be wrong. I can't change that, but you seem to have the 'Settings' gear, so you could.

In the Settings tab, you should look for the GitHub Pages section, and grab the correct url from there (this is an example from one of my sites, since I can't access the Glosario one):

<img width="883" alt="Screen Shot 2020-11-26 at 12 55 51" src="https://user-images.githubusercontent.com/12277715/100353718-d9eb6b80-2fe6-11eb-8d96-9d8983037efd.png">

**Comment by BatoolMM** [comment]
Yes, I've changed it but I want to double-check with @fmichonneau, just to clarify why are there two `URLs`?

Regarding rendering the website locally, can I ask what you meant by changing the repository identifier? Do you mean inside`.git/config`?

**Comment by baileythegreen** [comment]
In my version of the _config.yml file I have the name of my version of the repository.

Regarding the two URLs, one is just the location of ar.html (or the index.html file, following the link you did, originally) file on the internet. You can access the raw versions of all of the files this way:

<img width="1153" alt="Screen Shot 2020-11-26 at 13 15 35" src="https://user-images.githubusercontent.com/12277715/100355423-a231f300-2fe9-11eb-8c59-469af5c2d1fd.png">

**Comment by BatoolMM** [comment]
Thank you @baileythegreen. Everything makes sense now. 
BTW, I love the new layout with the `letter links` :)

**Comment by baileythegreen** [comment]
@BatoolMM Thank you. It's my first major foray into html/CSS. Hopefully I can improve it in the future to make it even nicer.
