### ISSUE TITLE
2020-12-16: Order of Languages in homepage

### ISSUE THREAD

**Issue by TomKellyGenetics** [carpentries/glosario#259]
Regarding the order of the entries (#254), the languages on the [homepage](https://glosario.carpentries.org/) may need to be changed for _consistency_ (this is done manually as I understand it).

In PR https://github.com/carpentries/glosario/pull/129 I added Japanese but it is under Portuguese by mistake (not sure if this was changed around the same time and merged awkwardly).  

https://github.com/carpentries/glosario/blob/3ddacca7561222220af08c910b10b1a7981c1635/_config.yml#L114_L127

I wasn't sure whether to sort alphabetically by roman letters (e.g. `de, en, fr, it, ja, nl, pt`) or use romansied names 日本語(Nihongo) as discussed [here](https://ux.stackexchange.com/questions/17064/how-do-you-sort-a-list-of-languages) or sort by language name in endonyms as done [here](https://stackoverflow.com/questions/3637341/is-there-a-proper-order-for-listing-languages) with other alphabets, abjad, and CJK characters at the end:

|Endonym  | Romanised | English name | ISO 639-1 | ISO 639-2 |
|:--------:|:----------:| :-------------:|:---------:|:-----------:|
|Afrikaans ||| af | afr|
|Català | | Catalan |ca | cat |
|Deutsch   |   | German | de | deu |
|English     | | | en | eng|
|Español  || Spanish |es| span |
|Français ||French | fr | fra |
|Nederlands || Dutch | nl |nld|
|Polski || Polish |po |pol |
|Ελληνικά | Elliniká | Greek | el | gre |
|עִבְרִית‎| Ivrit | Hebrew |he|heb|
|Русский язык | rússkiy yazýk | Russian | ru | rus| |
|العربية | al-ʿarabiyyah | Arabic | ar | ara|
|हिन्दी|  Hindī | | hi | hin |
|ภาษาไทย | Phasa Thai | Thai    |  th    | tha |
|한국어   | Hangug-eo | Korean   | ko | kor |
|简体中文   |   Jiǎntǐ Zhōngwén | Chinese (simplified) | zh_ch   | chi | 
| 繁體中文  | Fántǐ Zhōngwén |  Chinese (traditional) |zh_tw zh_hk | zho|
|日本語|   Nihongo   | Japanese | ja | jpn   |

So either we sort Japanese as "ja", "nihongo", or put it at the end as a special character (in which case Arabic would be moved as well).

**Comment by baileythegreen** [comment]
The order of languages on the homepage is not ever sorted. It is determined entirely by the order of the entries in `_config.yml`. If you look, you will see that Japanese in this file is below Portuguese.

I gather that the number of languages that exist in this project has grown fairly quickly. Before it gets out-of-hand, we should consider whether it makes sense to have a home page that lists all of the languages and their respective blurbs in *some order*, or:

1. either detect the language settings of the [computer/browser](https://stackoverflow.com/questions/18185284/how-to-detect-client%C2%B4s-computer-language-or-what-ever-in-order-to-change-langu) as this post asks (not something I know how to do at the moment, but I can learn which variables to use), or
1. just have a dropdown menu where people can choose their language, as many sites do. I don't see the mechanics and CSS for that being terribly difficult.

**Comment by TomKellyGenetics** [comment]
> The order of languages on the homepage is not ever sorted. It is determined entirely by the order of the entries in _config.yml. If you look, you will see that Japanese in this file is below Portuguese.

I understand that, I'm suggesting to decide on a consistent order to manually change it (as it only needs to be done once) and make sure that new languages are added correctly. The problem seems to be non-Latin writing systems as it's not clear where to sort them.

Of course if either of your suggested solutions are implemented this would be no longer relevant. They're both good ideas but I actually like the home page giving an overview of how many languages are supported as it is.

**Comment by ian-flores** [comment]
Fixed in #260
