### ISSUE TITLE
2021-02: Auto-generate links to individual entries

### ISSUE THREAD

**Issue by drj11** [carpentries/glosario#284]
I just sent a link to https://glosario.carpentries.org/en/#regression_testing to someone in chat to explain regression testing.

So, while it is possible to link to individual entries (because they have `id` attributes), it wasn't obvious how.

Can we have those hover-over (chain) link things that things like readthedocs do? (example: hover over the section title: https://python-3-for-scientists.readthedocs.io/en/latest/python3_features.html#file-path-manipulation)

**Comment by baileythegreen** [comment]
Maybe! That sounds like it relates to some things I've done. And I've inspected the page you sent. Looks like something that could be programmatically generated easily enough.

I can look at it later.

(The rest of this is just notes for myself, and mutilated html so it will all be visible.)

`<h2>File path manipulation
           <a class="headerlink"
              href="#file-path-manipulation"
              title="Permalink to this headline">¶
           </a>
</h2>`

<
h2>File path manipulation
           <
              a class="headerlink"
              href="#file-path-manipulation"
              title="Permalink to this headline">¶
           <
              /a>
<
/h2>

**Comment by froggleston** [comment]
Fixed in #743

**Comment by elletjies** [comment]
@all-contributors please add @drj11 question
