### ISSUE TITLE
Consider a neutral point of view as a requirement for definitiions

### ISSUE THREAD

**Issue by jduckles** [carpentries/glosario#29]
Looking through the definitions I found the definition of "falsy" as "A horrible neologism....". 

Should a glossary be so judgemental of the reader's perspectives on the term "falsy"?  

Please consider adopting a Neutral Point of View for glossary definitions. The [Wikipedia NPOV](https://en.wikipedia.org/wiki/Wikipedia:Neutral_point_of_view) is a good example

**Comment by ian-flores** [comment]
I think @jduckles raises a valid point, in which at least we shouldn't add valorations to the definitions. The Wikipedia entry seems to be quite clear about how to proceed about this. I think if @jduckles could flag all of the instances and raise them as a PR we could merge it quickly. 

@gvwilson @fmichonneau @zkamvar comments?

**Comment by gvwilson** [comment]
The definitions of "truthy" and "falsy" were meant humorously. No objection to them being changed.

**Comment by jduckles** [comment]
Closing as merge of #43 addressed the issue.

**Comment by elletjies** [comment]
@all-contributors please add @jduckles question
