### ISSUE TITLE
[2021-05-06]: [Italian]

### ISSUE THREAD

**Issue by lucaferranti** [carpentries/glosario#311]
Hi everyone,

this project looks like fun. I'd be glad to contribute with my mother language (Italian). I noticed the language is not supported yet, should I open a PR to add the infrastructure? I guess I could figure out how to do it by reverse engineering #224, but I wanted to double check first that adding a new language is not an "admin privilege", as I didn't find instructions about it in the `CONTRIBUTING.md`.

cheers
luca

**Comment by fmichonneau** [comment]
Hi Luca,

Feel free to submit a PR to add the infrastructure needed to support Italian. We'd love to have more languages supported. We are looking forward to your contributions. Would you also be willing to be an editor for the Italian language?

Thanks!

**Comment by lucaferranti** [comment]
I am not sure what you mean by editor exactly, but if it means being willing to keep adding translations and review others' PR than sure count me in.

**Comment by zkamvar** [comment]
Hi Luca,

You are correct that the documentation needs to be updated for adding a new language. I believe what you need to do is to create a markdown file that corresponds to your language that needs two things:

1. a YAML header that specifies the permalink relative to the root of the site (i.e. `permalink: /it/`). 
2. the main body should be `{% include glosarry.html %}` for Jekyll to insert the Italian content from the main glossary.

For example, https://github.com/carpentries/glosario/blob/master/es.md

**Comment by lucaferranti** [comment]
thank you for the instructions. From what I could tell by reverse engineering #224 , I also updated the `_config.yml` and added the language code to `utils/check-glossary.py`, no idea what this last one does though :D. Anyway, I opened a PR #313, let me know if I got some settings wrong

**Comment by fmichonneau** [comment]
Thanks Luca! I invited you to join the "glosario-editors-it" team. 

If you'd like, you can also join The Carpentries Slack (https://swc-slack-invite.herokuapp.com/) and there, we have a glosario channel.
