### ISSUE TITLE
6/1/2021: Lesson Contribution of Amharic Translation

### ISSUE THREAD

**Issue by Talishask** [carpentries/glosario#323]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

Please see the attached lesson contribution
[Glossary_Amharic 1_final.docx](https://github.com/carpentries/glosario/files/6577725/Glossary_Amharic.1_final.docx)

**Comment by elletjies** [comment]
@elletjies and @tobyhodges will be working to merge the contribution into Glossario
