### ISSUE TITLE
2021-09-07: Lesson Contribution English to Germany

### ISSUE THREAD

**Issue by Talishask** [carpentries/glosario#374]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---
Contribution

entry from the English glosario

https://glosario.carpentries.org/en/

translation for the entry for the German glosario

https://glosario.carpentries.org/de/

big data

Any data that until recently was too big for most people to work with on a single computer.

Big Data

Alle Datenmengen, die bis Kurzem vor zu umfangreich für die Analyse mit nur einem Computer waren.

bit

A unit of information representing alternatives, yes / no; true/false. In computing a state of either 0 or 1.

Bit

Ein Bit ist eine Informationseinheit, die nur zwei Alternativen darstellen kann. Beispiele hierfür sind Ja/ Nein, Wahr / Falsch. In der Computerwelt als 0 und 1 dargestellt.

bug

A missing or undesirable feature of a piece of software; the digital equivalent of a weed.

Bug

Ein Bug ist ein Fehler oder Fehlfunktion einer Software.

bug report

A collection of files, logs or related information that describes either an unexpected error or warning. This is used to help find and fix a bug in a program or code.

Fehlerbericht

Ein Fehlerbericht ist eine Sammlung von Dateien / Einträgen oder damit zusammenhängenden Informationen, die einen unbeabsichtigten Fehler beschreiben. Der Fehlerbericht wird für die Identifikation und Behebung seines Softwarefehlers / Codefehlers gebraucht.

byte

A unit of digital information that typically consists of eight binary digits, or bites.

Byte

Ein Byte ist eine digitale Einheit, die aus acht Binärziffern oder Bits besteht.

**Comment by jsteyn** [comment]
These term all seem to have been added so I'll close this issue.
