### ISSUE TITLE
05.10.2021 - Adding multiple German translations and change one definion

### ISSUE THREAD

**Issue by MRudey** [carpentries/glosario#389]
Hi,
As part of my checkout procedure I decided to translate a larger amount of the terms in the glossary. I made separate [commits](https://github.com/carpentries/glosario/compare/main...MRudey:MRudeyGerman) for each of them. Along the way I also added some links to other entries when I came across it and found a wrong definition of boilerplate code (should I create a separate issue for this?). 

Should I split the pull requests into smaller parts or should I simply reference this issue?

## Terms translated:

- aggregation_function
- agile
- aliasing
- anonymous_function
- api
- argument
- ascii
- assertion
- associative_array
- asynchronous
- attribute
- auto_completion
- backpropagation
- bias
- binary
- block_comment
- binary
- boilerplate
- boolean
- breadcrumbs
- callback
- camel_case
- catch_expression
- causation
- cc_0
- cc_by
- cc_license
- parameter

## Terms changed:
- boilerplate
The previous definition stated that boilerplate code is 

> Standard text that is included in legal contracts, licenses, and so on.

However, [wikipedia](https://en.wikipedia.org/wiki/Boilerplate_code) says that: 

> In computer programming, boilerplate code or just boilerplate are sections of code that are repeated in multiple places with little to no variation. When using languages that are considered verbose, the programmer must write a lot of code to accomplish only minor functionality. Such code is called boilerplate.

The definition now reads: 
> Parts of the source code that have to be repeated very often to get basic functionality.
In `[object-oriented programs](#oop)` these segments are used to encapsulate variables
of objects. Some languages require a lot of these statements and are termed boilerplate
languages, e.g. Java, which means that they are frequently generated automatically or by
using `[auto-completion](#auto_completion)`.

**Comment by fmichonneau** [comment]
You can submit a single pull request given that you have already done the work.

I had never heard this definition for boilerplate but was familiar with the one currently included in the glossary. Should we include both? 

Thanks!

**Comment by elletjies** [comment]
@all-contributors please add @MRudey question

**Comment by elletjies** [comment]
@all-contributors please add @konrad  question
