### ISSUE TITLE
2021-10-15: README contains two typos that make an example not work

### ISSUE THREAD

**Issue by larnsce** [carpentries/glosario#400]
In [Use Cases - 1. Linking a definiton](https://github.com/carpentries/glosario/blob/main/README.md#use-cases) a hyphen '-' instead of an underscore '_' was used for the example. When using the example the resulting glossary page does not jump to the entry but to the top of the page.

**Comment by elletjies** [comment]
@all-contributors please add @larnsce  question

**Comment by elletjies** [comment]
@all-contributors please add @zkamvar  question
