### ISSUE TITLE
missing definition for R programming language in Setsawana

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/glosario#441]
in 1bf97054c3f1f330ac9ec065f99cd2257c71297c the definition of the term is missing.

@elletjies do you have it? Thanks!

**Comment by elletjies** [comment]
@fmichonneau no we don't - can we add the English for now?

**Comment by fmichonneau** [comment]
the English definition is already present, so we are all set. If you don't have the definition available for now, I'm going to close the issue. Thanks!
