### ISSUE TITLE
[30-11-2021]: [Add Sesotho]

### ISSUE THREAD

**Issue by elletjies** [carpentries/glosario#463]
Hi, 

Can we add Sesotho to the offerings list?

**Comment by fmichonneau** [comment]
yes! do you already have translations for entries or the description of the project?

**Comment by elletjies** [comment]
@fmichonneau we have two translations here (https://docs.google.com/spreadsheets/d/1b9EFCyZOrgx_impWDcNcA7KLnfSysM-UvWfmledCnAY/edit#gid=0) - but no translation of the description of the project yet. I am going to reach out to the community to ask if they can assist :)
