### ISSUE TITLE
January 12, 2022: index sidebar not useful

### ISSUE THREAD

**Issue by vdike** [carpentries/glosario#465]
Using Firefox in Ubuntu on a fairly large desktop monitor, when I open glosario (https://glosario.carpentries.org/en/) the letter-index is a sidebar in which the bottom letters aren't accessible unless I scroll to the bottom of the page, negating the purpose of having such an index in the first place. For example, if I wanted to look up 'virtual machine' on my screen the clickable index letter 'V' is cut off so I can't just click on it to get to the relevant entry that way. If possible, the clickable letter-index should be made to fit on the top of the page.

**Comment by elletjies** [comment]
@all-contributors please add @vdike  question
