### ISSUE TITLE
11 February 2022: Suggested addition of "autocorrelation" (checkout)

### ISSUE THREAD

**Issue by karenword** [carpentries/glosario#468]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

----------------

I have a proposed word to add to Glosario:

Autocorrelation: The degree of similarity between observations in the same series but separated by a time interval (known as the "lag"). Autocorrelation analysis can be used to gain insight into time series datasets by detecting repeating patterns that may be partially concealed by random noise, among other uses.

Thank you for your time.

**Comment by Ltressel** [comment]
I agree with the addition of the word "Autocorrelation" to the Glosario page. Having worked with time-series datasets myself,  I use autocorrelation analyses pretty often. This definition is accurate, and useful.

**Comment by jsteyn** [comment]
I'll add the term

**Comment by jsteyn** [comment]
Ådded. #485

**Comment by elletjies** [comment]
@all-contributors please add @karenword  question
