### ISSUE TITLE
[9.5.2022.]: [Croatian]

### ISSUE THREAD

**Issue by IngaPa** [carpentries/glosario#489]
Dear community, I would love to translate the glossary to Croatian. With whom should I get in touch in order to do so?

warm wishes,
I

**Comment by klbarnes20** [comment]
@fmichonneau and @zkamvar could you help @IngaPa?

**Comment by zkamvar** [comment]
Hello, we have instructions for adding a new language here: https://github.com/carpentries/glosario/blob/main/CONTRIBUTING.md#adding-a-new-language

**Comment by fmichonneau** [comment]
added with #492

**Comment by elletjies** [comment]
@all-contributors please add @IngaPa  question
