### ISSUE TITLE
[2022-09-08]: [Chinese-中文]

### ISSUE THREAD

**Issue by lingmeng634** [carpentries/glosario#525]
The title of Chinese should use the native language "中文" not "Chinese" like the other languages. (Example: 日本語 for Japanese)

**Comment by zkamvar** [comment]
Thank you @lingmeng634. Would you like to submit a PR to make the change? The line to change is: 

https://github.com/carpentries/glosario/blob/57a049cfacf2598ffb0453bc8440668c4bdc11f9/_config.yml#L288

I am also happy to make the change if you are not comfortable making a PR.

**Comment by zkamvar** [comment]
Fixed in #575

**Comment by lingmeng634** [comment]
Dear Zhian,

Does this mean you've made the change? Sorry I forgot to replay and thanks
for your help.

Best,
Ling

Zhian N. Kamvar ***@***.***> 於 2023年3月6日 週一 上午11:53寫道：

**Comment by zkamvar** [comment]
> Dear Zhian, Does this mean you've made the change? Sorry I forgot to replay and thanks for your help.

Hi @lingmeng634, @cmdalton made the fix, I just merged it :)

Thank you for opening the issue

**Comment by elletjies** [comment]
@all-contributors please add @lingmeng634  question
