### ISSUE TITLE
15/08/2020: Idea for Template - languages other than English

### ISSUE THREAD

**Issue by beatrizmilz** [carpentries/glosario#53]
Hi!
I would like to say an idea.
I think it would be good to show in the pages of Glosario of other languages rather than English, the term in English aswell.

A example situation to ilustrate: Gabriela speaks portuguese. She is reading a tutorial about R in english and she wants to know what is a `current working directory`. She opens the Glosario in portuguese ( https://carpentries.github.io/glosario/pt/ ) and tries to find it. But in portuguese this term is `diretório de trabalho` , and does not find the definition. If glosario also showed the term in English (because is the language most used in tutorials, courses, books), it would be easier to find. 

Example: 
![image](https://user-images.githubusercontent.com/42153618/90314707-21dcfb80-deec-11ea-978d-c4f6ba804d73.png)

I'm not sure if this goes out of the scope of Glosario, is just an idea that I think it could make easier to people consult Glosario while studying DS. 

Thank you!

**Comment by beatrizmilz** [comment]
GitHub added the label of bug, but it's just a idea. I'm not able to chage the label

**Comment by elletjies** [comment]
@all-contributors please add @beatrizmilz question
