### ISSUE TITLE
[2022-12-12]: [Hungarian | Magyar]

### ISSUE THREAD

**Issue by notimre** [carpentries/glosario#556]
### Request:

Please add 'Hungarian' (in English) or 'Magyar' (in Hungarian) on the right handside at [Glosario](https://glosario.carpentries.org/)
IETF language tag: 'hu'

### Background
I have recently completed my Carpentries Instructor Training Course.
In order to get my certification, I would like to add Hungarian translation to the Glossary.

Since the Language is not available at all, I would like to start it.

**Comment by zkamvar** [comment]
Hello @notimre, we have [instructions for adding a new language page](https://github.com/carpentries/glosario/blob/main/CONTRIBUTING.md#adding-a-new-language). You can try it out as a pull request or I can create it if you wish.

**Comment by elletjies** [comment]
Thanks @zkamvar and @notimre!
