### ISSUE TITLE
2023-01-10: Lesson Contribution - Some Translations

### ISSUE THREAD

**Issue by Talishask** [carpentries/glosario#559]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

**English**
Data directory (DataDir) The root directory for the CUPS data files. By default/usr/share/cups.

**Afrikaans**
Data gids (DataDir) Die root gids vir Die cups data lêers. Deur verstek/usr/deel/cups. bv:/usr/deel/cups.

**English**
Data Frame: A two- dimensional data structure for storing tabular data in memory. Row represent records and columns represent variables.

**Kiswahili**
Data Fremu: Muundo wa data wa pande mbili wa kuhifadhi data ya tabular katika kumbukumbu. Safu zinawakilisha rekodi na nguzo zinawakilisha vigezo.

**English**
Directory: An item within a file system that can contain files and other directories. Also known as a folder.

**Kiswahili**
mpangilio orodha: Kipengee ndani ya mfumo wa faili ambao unaweza kuwa na faili na saraka zingine. Pia inajulikana kama folda.

**English**
Folder: Another term for a directory.

**Kiswahili**:
Kabrasha: Neno lingine kwa saraka

**Comment by elletjies** [comment]
@Talishask thanks for the submission - do we know the author perhaps?
