### ISSUE TITLE
2023-04-07: Reference links to parametric (statistics) and non-parametric (statistics) are broken

### ISSUE THREAD

**Issue by rosemm** [carpentries/glosario#580]
The reference links at https://glosario.carpentries.org/en/#parametric_statistics and https://glosario.carpentries.org/en/#nonparametric_statistics don't work. 
I'm not sure if this is related, but nonparametric_statistics is also displaying as the first entry in the glossary instead of correctly alphabetized under N.

**Comment by rosemm** [comment]
I haven't submitted to glosario before, but I'm happy to attempt a fix to the ref issue! I'll submit a PR for review.

**Comment by elletjies** [comment]
@all-contributors please add @rosemm  question
