### ISSUE TITLE
[2024-06-24]: [Alphabetical ordering for Ukrainian and Portuguese languages]

### ISSUE THREAD

**Issue by olexandr-konovalov** [carpentries/glosario#724]
The right navigation bar with letters at https://glosario.carpentries.org/uk/ does not follow the order of letters in Ukrainian alphabet, placing  "І" at the last place. Is there a way to enforce the fixed order of the letters?

 
![Screenshot 2024-06-24 at 18 53 38](https://github.com/carpentries/glosario/assets/5751387/a9baeeff-df2e-4319-b3e1-9895465f2c6d)

**Comment by olexandr-konovalov** [comment]
It seems to me the issue is not with the navigation bar, but with terms being ordered in the wrong way in the first instance. I have traced this to 
https://github.com/carpentries/glosario/blob/b7d10b315e6e2b34572dfab4c5692187ec5fb225/_includes/glossary.html#L9C1-L9C61
but I don't know where to go from here.

**Comment by YehorBoiar** [comment]
Could it be because we don't have all letters for all terms? So it just ordered ones that only exist

**Comment by olexandr-konovalov** [comment]
@YehorBoiar we can of course try to push for more translations to cover more Ukrainian letters - new PRs welcome :) 

But I don't think that "І" at the last place depends somehow on that. That is perhaps due to Unicode codes playing the role. Similar problem for Portuguese in https://glosario.carpentries.org/pt/ where Â is not after A, but at the very end. I don't have any knowledge of Portuguese to comment on this, but https://portuguese.stackexchange.com/questions/5797/do-diacritical-marks-accents-affect-alphabetical-sorting-of-words suggests that this is not the way it should be.

**Comment by olexandr-konovalov** [comment]
P.S. Indeed the unicode code seems to be relevant: compare Ukrainian alphabet by position in alphabet at https://en.wikipedia.org/wiki/Ukrainian_alphabet with the Ukrainian character table at https://character-table.netlify.app/ukrainian/. So the question is as before - how to introduce sorting in a properly alphabetical order?

**Comment by froggleston** [comment]
This will be down to how liquid and jekyll implement their `sort` filter.

It seems that they sort by unicode rather than natural ordering in that specific language: 
* https://github.com/jekyll/jekyll/issues/2135

Relevant other info:
* https://www.rubydoc.info/gems/activesupport/ActiveSupport/Inflector#transliterate-instance_method
* https://stackoverflow.com/questions/4127812/sort-list-based-on-their-i18n-translation

**Comment by froggleston** [comment]
Related to https://github.com/carpentries/glosario/issues/254

**Comment by olexandr-konovalov** [comment]
Would it be possible to provide correct sorting for each language explicitly (and request providing that as a part of adding new languages)?

**Comment by olexandr-konovalov** [comment]
Excellent - thanks @froggleston!
