### ISSUE TITLE
2020-09-17: rendering glitch in definition of Bayes Theorem

### ISSUE THREAD

**Issue by gvwilson** [carpentries/glosario#85]
Viewing English version of glossary, Bayes' Theorem shows as below:

![Screen Shot 2020-09-17 at 10 00 22 AM](https://user-images.githubusercontent.com/911566/93481649-c88e3080-f8cc-11ea-980c-ba96f22809ea.png)

**Comment by zkamvar** [comment]
I believe this is a problem on the Jekyll side. It is parsed okay on the R side: 

``` r
g <- glosario::get_glossary()
g$define("bayes_theorem")
#> Bayes' Theorem: An equation for calculating the probability that something is
#>   true if something related to it is true. If P(X) is the probability that X is
#>   true and P(X|Y) is the probability that X is true given Y is true, then
#>   P(X|Y) = P(Y|X) * P(X) / P(Y).
#> See also: bayesian_network, naive_bayes_classifier, and prior_distribution
#> 
```

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fmichonneau** [comment]
yes, Jekyll interprets the `|` as column delineators for a table:
[
![Screenshot from 2020-09-21 15-26-03](https://user-images.githubusercontent.com/5502922/93772239-9a6e6080-fbec-11ea-8c80-893cc61fdd1e.png)
](url)

**Comment by fmichonneau** [comment]
it looks like we need to escape the `|` in the definition...

I think we want to keep the `markdowify` filter and that implies that any later alteration of the output (e.g., using `remove`) means that the `|` would be lost.

**Comment by zkamvar** [comment]
The spec for kramdown is much looser than GFM or other parsers: https://kramdown.gettalong.org/quickref.html#tables

Newer versions of kramdown have GFM as an option, so maybe we can add that as the parser for markdown inside the elements? The only problem I can see is that GFM keeps the original line breaks, so the text will flow weird on smaller screens.
