### ISSUE TITLE
2020-09-24: Add pronunciation

### ISSUE THREAD

**Issue by gvwilson** [carpentries/glosario#90]
As per https://twitter.com/neilccbrown/status/1309124732604874759, adding short audio snippets to show people how to pronounce things would be cool.

**Comment by ian-flores** [comment]
This sounds very useful. Two things pop into my mind about managing it: 1) Who would do the recordings and would it be only for 1 language? 2) Where would we store the recordings? I imagine something separate from this repo like a very structured Cloud bucket but then we go into expenses like cloud billing.

**Comment by fmichonneau** [comment]
storage of the recordings (e.g., on AWS S3) is not a problem.
