### ISSUE TITLE
2020-09-28: DefinedTerm & DefinedTermSet for metadata 

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/glosario#97]
What's the rationale behind your suggestion of `glossary` metadata in the README vs. using existing standards such as [_DefinedTermSet_](https://schema.org/DefinedTermSet) and [_DefinedTerm_](https://schema.org/DefinedTerm) from Schema.org? Or is the intention that tools would convert this YAML metadata description into HTML `itemscope`/`itemprop`/`meta` tags or a JSON-LD blob, which would then use these specifications, in the page created from the source file? (e.g. When the RMarkdown file is knitted to HTML.)

**Comment by gvwilson** [comment]
We wanted to minimize typing - past efforts to get people to type tags have mostly foundered. (I did once mark up a document at the level of `<person><personal-name>Greg</personal-name> <family-name>Wilson</family></person>` - never again...) We think the YAML is structured enough to support conversion to more tightly defined formats - the only thing that might be problematic is the embedded cross-references in definitions, but provided internal Markdown links are _only_ used for that purpose within `glossary.yml`, it seems that regular expressions are reliable enough to spot them.

**Comment by tobyhodges** [comment]
Thanks @gvwilson. As I read more and more about this today I started to realise that yours was probably the answer to my question. Good to get more context though.

**Comment by elletjies** [comment]
@all-contributors please add @tobyhodges question
